<a href="https://colab.research.google.com/github/MDHussain2004/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#QUESTION1
#Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it  enhance Python's capabilities for numerical operations?
'''
NumPy (Numerical Python) is a powerful library in Python that provides support for large, multi-dimensional arrays and matrices, along with a vast collection of mathematical functions to operate on these arrays efficiently. It is widely used in scientific computing and data analysis due to its performance, ease of use, and ability to handle large datasets.

Purpose of NumPy:
Efficient Numerical Computations:

NumPy allows for fast and efficient operations on large datasets, including element-wise operations, matrix operations, and other numerical computations.
It is implemented in C, making it much faster than using Python’s built-in data structures like lists for numerical calculations.
Multi-dimensional Array Support:

NumPy introduces the ndarray object, which is a powerful N-dimensional array used to store data in a structured format.
Arrays can be indexed, sliced, and manipulated in various ways, making it ideal for working with datasets of any dimension.
Mathematical Functions and Linear Algebra:

NumPy provides a wide variety of mathematical functions (e.g., trigonometric, logarithmic, exponential) and linear algebra operations (e.g., matrix multiplication, eigenvalue computation).
Interfacing with Other Libraries:

Many libraries in scientific computing, machine learning, and data analysis, such as SciPy, Pandas, and TensorFlow, are built on top of NumPy and make extensive use of its arrays and functions.
Advantages of NumPy in Scientific Computing and Data Analysis:
Speed and Performance:

NumPy operations are much faster than equivalent operations on Python lists because they are implemented in C, and NumPy arrays are more memory-efficient. This results in significant performance improvements, especially for large datasets.
Vectorization and Broadcasting:

NumPy supports vectorized operations, meaning you can perform operations on entire arrays without the need for loops, which significantly speeds up computations.
Broadcasting allows you to perform arithmetic operations on arrays of different shapes and sizes in a way that is both intuitive and efficient.
Memory Efficiency:

NumPy arrays use less memory compared to Python lists because they store data in contiguous blocks of memory, avoiding the overhead associated with lists
 that store pointers to objects.
Support for Multi-dimensional Data:

NumPy arrays (ndarrays) support multi-dimensional data, which is essential for tasks like image processing, scientific simulations, or machine learning, where data
 often comes in the form of matrices or higher-dimensional structures.
Rich Mathematical Operations:

NumPy provides a wide range of mathematical operations (e.g., addition, subtraction, matrix multiplication, dot product) and supports linear algebra, Fourier transforms,
 and random number generation, all optimized for performance.
Integration with Other Libraries:

NumPy seamlessly integrates with libraries like Pandas (for data manipulation), Matplotlib (for plotting), SciPy (for scientific computing), and TensorFlow (for machine learning).
 This ecosystem makes it indispensable in data science and engineering applications.
How NumPy Enhances Python's Capabilities:
Array-based Data Structures:
Python’s built-in data structures (like lists) are flexible but not optimized for numerical operations. NumPy’s ndarray provides an efficient way to store and manipulate numerical
data, enabling faster and more reliable numerical computations.
Faster Execution:
Python is an interpreted language and can be slow for loops or element-wise operations on lists. NumPy enhances performance by offloading operations to highly-optimized C libraries,
making numerical operations much faster.
Mathematical Routines:
Python alone lacks robust support for high-performance linear algebra, random number generation, and other numerical routines. NumPy adds these capabilities, allowing Python to
be used effectively for scientific and mathematical computing.
'''
#Example: NumPy Array vs Python List
import numpy as np

# NumPy array operations
arr = np.array([1, 2, 3, 4])
print(arr * 2)  # Element-wise multiplication (Vectorization)
# Output: [2 4 6 8]

# Python list operations (without NumPy)
lst = [1, 2, 3, 4]
print([x * 2 for x in lst])  # Slower due to looping
# Output: [2, 4, 6, 8]

#In this example, NumPy performs element-wise multiplication without the need for an explicit loop, making it faster and more readable than using a Python list.

[2 4 6 8]
[2, 4, 6, 8]


In [ ]:
#QUESTION 2
#Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the  other?
'''
Both np.mean() and np.average() are NumPy functions used to compute the average of values, but they have different behaviors, especially when dealing with weighted averages.
Here's a comparison of the two functions and when to use each:

1. np.mean():
Purpose: Computes the arithmetic mean (average) of the elements along the specified axis.
Parameters:
a: Input array or object that can be converted to an array.
axis: (Optional) Axis or axes along which the means are computed. The default is to compute the mean of the flattened array.
dtype: (Optional) Data type for the result. The default is inferred from the input array.
keepdims: (Optional) If set to True, retains reduced dimensions with size 1.
Behavior: It always returns the arithmetic mean, where all elements contribute equally.
'''
#Example:

import numpy as np

data = np.array([1, 2, 3, 4, 5])

# Compute arithmetic mean
mean_value = np.mean(data)
print(mean_value)  # Output: 3.0
'''
2. np.average():
Purpose: Computes the weighted average of the array elements, which means elements can have different "weights" in the computation.

Parameters:

a: Input array or object that can be converted to an array.
weights: (Optional) An array of weights associated with the values in the input array. If not provided, it computes the arithmetic mean (like np.mean()).
axis: (Optional) Axis or axes along which to average.
returned: (Optional) If True, returns a tuple with the average and the sum of the weights.
Behavior:

If weights are not provided, np.average() behaves like np.mean().
If weights are provided, it computes a weighted average, where each element in the array contributes to the result according to its associated weight.
Example without weights (behaves like np.mean()):
'''

data = np.array([1, 2, 3, 4, 5])

# Compute average (without weights, same as mean)
average_value = np.average(data)
print(average_value)  # Output: 3.0


data = np.array([1, 2, 3, 4, 5])
weights = np.array([0.1, 0.2, 0.3, 0.4, 0.5])

# Compute weighted average
weighted_avg = np.average(data, weights=weights)
print(weighted_avg)  # Output: 3.6666666666666665
'''
Key Differences:
Aspect	np.mean()	np.average()
Default behavior	Computes the arithmetic mean.	Computes the arithmetic mean if no weights are given.
Weighted average	No support for weights.	Supports weighted averages using the weights parameter.
Return value	Returns the mean.	Returns the weighted average (and sum of weights if returned=True).
Use case	When you need the simple arithmetic mean of an array.	When you need a weighted average of the array.
When to Use np.mean():
Use np.mean() when you need to compute the arithmetic mean and do not need to account for weights.
It's simpler, faster, and should be your go-to function for basic averaging.
'''
#Example Use Case:

data = np.array([10, 20, 30, 40])
mean_val = np.mean(data)  # Output: 25.0
'''
When to Use np.average():
Use np.average() when you need to compute a weighted average, where some elements of the array have more influence on the result than others.
If you don't pass the weights argument, np.average() is equivalent to np.mean().
'''
#Example Use Case (Weighted Average):

# Weights reflecting different importance of the elements
data = np.array([10, 20, 30, 40])
weights = np.array([1, 2, 3, 4])
weighted_avg = np.average(data, weights=weights)  # Output: 30.0

#In this example, the higher weight for the last elements means the values 30 and 40 contribute more to the weighted average than 10 and 20.

3.0
3.0
3.6666666666666665


In [ ]:
#QUESTION 3
# Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.
'''
In NumPy, you can reverse arrays along different axes using slicing, specialized functions, or methods like np.flip(). Here’s a breakdown of how to reverse arrays for
both 1D and 2D arrays.

1. Reversing a 1D NumPy Array
The simplest way to reverse a 1D NumPy array is by using Python slicing.

Method 1: Slicing
You can reverse a 1D array using the slicing method [::-1].
'''
import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse using slicing
reversed_arr_1d = arr_1d[::-1]
print(reversed_arr_1d)  # Output: [5 4 3 2 1]

#Method 2: np.flip()
#You can also use the np.flip() function to reverse a 1D array along a specific axis.
reversed_arr_1d_flip = np.flip(arr_1d)
print(reversed_arr_1d_flip)  # Output: [5 4 3 2 1]
'''
2. Reversing a 2D NumPy Array
For a 2D array, reversing can be done along different axes (rows, columns, or both).

Method 1: Reverse Along Rows (Axis 0)
To reverse the array along the rows (flip vertically):
'''
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reverse along rows using slicing
reversed_rows = arr_2d[::-1, :]
print(reversed_rows)
'''
Method 2: Reverse Along Columns (Axis 1)
To reverse the array along the columns (flip horizontally):
'''
# Reverse along columns using slicing
reversed_columns = arr_2d[:, ::-1]
print(reversed_columns)
'''
Method 3: Reverse Along Both Axes
To reverse the array along both axes (flip both rows and columns):
'''
# Reverse along both axes using slicing
reversed_both = arr_2d[::-1, ::-1]
print(reversed_both)
'''
Method 4: np.flip()
You can use the np.flip() function to reverse a 2D array along a specific axis.
'''
#Flip along rows (axis 0):
reversed_rows_flip = np.flip(arr_2d, axis=0)
print(reversed_rows_flip)

#Flip along columns (axis 1):

reversed_columns_flip = np.flip(arr_2d, axis=1)
print(reversed_columns_flip)

#Flip along both axes:

reversed_both_flip = np.flip(arr_2d)
print(reversed_both_flip)


[5 4 3 2 1]
[5 4 3 2 1]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
#QUESTION 4
#How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.
'''
I can determine the data type of elements in a NumPy array using the .dtype attribute.
This attribute returns the data type of the array's elements, which is critical for efficient memory management and performance in NumPy.
'''
#Example: Determine the Data Type of a NumPy Array

# Creating an array
arr = np.array([1, 2, 3, 4])

# Checking the data type of the elements
print(arr.dtype)  # Output: int64 (or int32, depending on the system)
#In this example, the .dtype attribute shows the type of the elements in the array, which in this case is int64.
'''
Importance of Data Types in Memory Management and Performance
Memory Efficiency:

NumPy allows for explicit control over the data type of the elements in an array. By choosing the right data type (e.g., int32, int64, float32, float64), you can optimize
memory usage.
For example, using a float64 data type (64 bits or 8 bytes per element) for storing integers is inefficient if a smaller data type like int8 (8 bits or 1 byte per element)
suffices. This becomes especially important when dealing with large datasets.
'''
#Example: Memory efficiency with different data types:

arr_int32 = np.array([1, 2, 3, 4], dtype='int32')
arr_float64 = np.array([1, 2, 3, 4], dtype='float64')

print(arr_int32.nbytes)  # Output: 16 bytes (4 elements * 4 bytes)
print(arr_float64.nbytes)  # Output: 32 bytes (4 elements * 8 bytes)
#As seen, using float64 consumes more memory than int32.
'''
Performance:

Operations on NumPy arrays are highly optimized for specific data types. By using appropriate data types, you can significantly boost computational performance.
For instance, using float32 instead of float64 can speed up operations when high precision isn't required because fewer bytes are processed at a time.
'''
#Example: Performance difference:

import time

# Large arrays
arr_float32 = np.random.rand(1000000).astype('float32')
arr_float64 = np.random.rand(1000000).astype('float64')

# Measure time for operations
start = time.time()
np.sum(arr_float32)
print("Time for float32:", time.time() - start)

start = time.time()
np.sum(arr_float64)
print("Time for float64:", time.time() - start)
#Operations on float32 arrays are faster than on float64 arrays, as less memory is processed.
'''
Precision:

The choice of data type affects the precision of calculations. For example, float32 provides less precision than float64, which may lead to rounding errors in complex calculations.
For applications where precision is critical, such as scientific computing or financial analysis, it's important to use a higher precision data type like float64.
Interoperability with Other Libraries:

In data analysis and scientific computing, NumPy arrays often interface with other libraries like pandas, TensorFlow, or PyTorch. Ensuring the correct data types can help
maintain consistency and avoid errors when passing data between different frameworks.
For example, in machine learning, using float32 is common in frameworks like TensorFlow or PyTorch because it offers a good balance between precision and performance.'''

int64
16
32
Time for float32: 0.0010197162628173828
Time for float64: 0.0018131732940673828


"\nPrecision:\n\nThe choice of data type affects the precision of calculations. For example, float32 provides less precision than float64, which may lead to rounding errors in complex calculations.\nFor applications where precision is critical, such as scientific computing or financial analysis, it's important to use a higher precision data type like float64.\nInteroperability with Other Libraries:\n\nIn data analysis and scientific computing, NumPy arrays often interface with other libraries like pandas, TensorFlow, or PyTorch. Ensuring the correct data types can help maintain consistency and avoid errors when passing data between different frameworks.\nFor example, in machine learning, using float32 is common in frameworks like TensorFlow or PyTorch because it offers a good balance between precision and performance."

In [ ]:
#QUESTION 5
# Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
'''
In NumPy, an ndarray (short for N-dimensional array) is a powerful, high-performance data structure that represents arrays of any dimensionality. It is the core data structure
in NumPy, used for storing and manipulating numerical data in an efficient way. ndarray is highly optimized for vectorized operations and mathematical computations,
making it essential for scientific computing and data analysis.

Key Features of ndarray:
N-Dimensional:

ndarray can represent arrays with any number of dimensions (1D, 2D, 3D, etc.), making it versatile for a wide range of mathematical operations.

#Example:
1D: [1, 2, 3]
2D: [[1, 2], [3, 4]]
3D: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]'''
'''
Homogeneous Data Type:

All elements in an ndarray must have the same data type (int, float, etc.). This is different from Python lists, which can store elements of different types.
The data type of an ndarray is defined by its dtype attribute, ensuring that operations are optimized and consistent.
Vectorized Operations:

NumPy ndarray allows for element-wise operations without the need for explicit loops. These vectorized operations are much faster than traditional Python loops.
Example: Adding two arrays element-wise:
'''
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2  # Output: [5, 7, 9]

#Memory Efficient:
'''
ndarray uses a fixed-size block of memory to store its elements, making it more memory efficient than Python lists. Additionally, you can explicitly define data types to
reduce memory usage (e.g., float32 vs. float64).
Shape and Dimensions:

Each ndarray has an associated shape (number of rows, columns, etc.) and dimensions (ndim), which describe the structure of the array.
'''
#Example:
arr = np.array([[1, 2], [3, 4]])
print(arr.shape)  # Output: (2, 2)
print(arr.ndim)   # Output: 2 (2D array)

#Broadcasting:

#NumPy supports broadcasting, a feature that allows operations between arrays of different shapes as long as their dimensions are compatible.
#Example:

arr = np.array([[1, 2], [3, 4]])
scalar = 5
result = arr + scalar  # Output: [[6, 7], [8, 9]]

#Mathematical Functions:

#NumPy provides numerous mathematical functions (e.g., np.sum(), np.mean(), np.sin()) that operate directly on ndarray objects, taking advantage of vectorization.
#Example:

arr = np.array([1, 2, 3, 4])
print(np.mean(arr))  # Output: 2.5

#Slicing and Indexing:

#Like Python lists, ndarray supports slicing and indexing to access specific elements or subarrays. However, slicing in ndarray returns a view, not a copy, which is more efficient.
#Example:

arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:4]  # Output: [2, 3, 4]

#How ndarray Differs from Python Lists:
#Homogeneous vs. Heterogeneous Data:
'''
ndarray: All elements must be of the same data type.
Python List: Can contain elements of different types (e.g., int, str, float).
'''

list1 = [1, "hello", 3.5]  # Valid in Python list, but not in ndarray
#Memory Usage:
'''
ndarray: Uses contiguous memory blocks, which are more memory-efficient.
Python List: Stores elements as references to objects, leading to higher memory overhead.
Performance:

ndarray: Optimized for numerical computations. Vectorized operations allow for faster mathematical operations compared to loops in Python lists.
Python List: Slower in performing element-wise mathematical operations since explicit loops are required.
Example:
'''

arr = np.array([1, 2, 3])
result = arr * 2  # Element-wise multiplication: Output [2, 4, 6]

# Python List:
lst = [1, 2, 3]
result_lst = [x * 2 for x in lst]  # Slower, requires looping

#Mathematical Operations:
'''
ndarray: Supports element-wise operations like addition, multiplication, etc.
Python List: These operations are not natively supported; you have to manually loop over elements.
Dimensionality:

ndarray: Can handle multidimensional arrays (1D, 2D, 3D, etc.).
Python List: Can simulate multidimensional arrays, but without any built-in structure or optimized handling.
Example (2D array):
'''
arr_2d = np.array([[1, 2], [3, 4]])
print(arr_2d.shape)  # Output: (2, 2)

# In Python List, you would need nested lists:
list_2d = [[1, 2], [3, 4]]

(2, 2)
2
2.5
(2, 2)


In [1]:
#QUESTION 6
# Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations
'''
NumPy arrays (ndarray) offer significant performance benefits over Python lists, especially for large-scale numerical operations. These benefits arise from their underlying
implementation and optimizations for handling numerical data efficiently. Let's explore these performance advantages in detail:

1. Memory Efficiency
NumPy arrays are stored in contiguous blocks of memory, and all elements have the same data type (e.g., int32, float64), leading to more efficient memory usage.
Python lists, on the other hand, are arrays of pointers to Python objects, each with metadata such as type, size, and reference count. This introduces overhead, especially for
large lists.
'''
#Example: Memory Usage Comparison
import numpy as np
import sys

# NumPy array
arr_np = np.arange(1000000, dtype='int32')
print("NumPy array memory usage:", arr_np.nbytes, "bytes")  # Output: ~4MB

# Python list
arr_py = list(range(1000000))
print("Python list memory usage:", sys.getsizeof(arr_py), "bytes")  # Output: ~8MB
#NumPy uses around half the memory compared to a Python list of the same length, which is significant for large datasets.
'''
2. Speed and Vectorization
NumPy arrays support vectorized operations, meaning that mathematical and logical operations are applied element-wise to the entire array without the need for explicit loops.
This is much faster than using for-loops with Python lists, where operations are performed element by element.
'''
#Example: Element-Wise Addition
import numpy as np
import time

# NumPy array
arr_np = np.arange(1000000)

# Python list
arr_py = list(range(1000000))

# Timing NumPy operation
start_time = time.time()
arr_np = arr_np * 2  # Element-wise multiplication
print("NumPy operation time:", time.time() - start_time)

# Timing Python list operation
start_time = time.time()
arr_py = [x * 2 for x in arr_py]  # List comprehension
print("Python list operation time:", time.time() - start_time)

#In this example, NumPy performs the operation much faster because it avoids the overhead of looping in Python and leverages optimized C-based routines to perform
#operations directly in memory.
'''
3. Efficient Broadcasting
NumPy supports broadcasting, which allows for operations between arrays of different shapes and sizes without copying data. Broadcasting optimizes memory use
and simplifies mathematical operations, leading to more efficient computations compared to Python lists.
'''
#Example: Broadcasting in NumPy

import numpy as np

# Broadcasting a scalar to a NumPy array
arr_np = np.array([1, 2, 3, 4])
result_np = arr_np + 5  # Adds 5 to every element

print("NumPy result with broadcasting:", result_np)  # Output: [6 7 8 9]
#With Python lists, you would have to loop through each element to perform the same operation, making the code slower and more cumbersome.
'''
4. Lower-Level Optimizations (Written in C)
NumPy is implemented in C, which allows it to avoid Python's interpreter overhead. This results in faster execution times for numerical computations. Python lists, being higher-level, are slower due to the need for Python's dynamic typing and memory management.

NumPy arrays are optimized for CPU cache performance, taking advantage of SIMD (Single Instruction Multiple Data) instructions, which allow for faster processing of large data blocks.
Python lists, however, cannot take advantage of such optimizations, and every element access or modification involves more overhead.
5. Specialized Mathematical Functions
NumPy provides highly optimized mathematical functions (such as np.sum(), np.mean(), np.dot(), etc.) that operate on entire arrays at once, further reducing the need for loops and improving performance. These functions are often implemented in compiled C or Fortran, providing a significant speed boost compared to pure Python implementations.
'''
#Example: Summing Large Arrays
import numpy as np
import time

# NumPy array
arr_np = np.arange(1000000)

# Python list
arr_py = list(range(1000000))

# Timing NumPy sum
start_time = time.time()
np.sum(arr_np)
print("NumPy sum time:", time.time() - start_time)

# Timing Python list sum
start_time = time.time()
sum(arr_py)
print("Python list sum time:", time.time() - start_time)
#NumPy's np.sum() is much faster than Python's built-in sum() due to the highly optimized C-based implementation.
'''
6. Multidimensional Array Support
NumPy is designed for handling multidimensional arrays (e.g., 2D, 3D, etc.) efficiently, with built-in support for slicing, reshaping, and
performing operations along different axes. In Python, creating and manipulating multidimensional lists requires complex, manual work with nested lists.
'''
#Example: 2D Array Manipulation

import numpy as np

# 2D NumPy array
arr_np = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose the array
arr_np_transposed = arr_np.T  # Efficient in NumPy
print(arr_np_transposed)
#With Python lists, the same operation would require explicit loops and complex code.
'''
7. Memory Views and Slicing
In NumPy, slicing an array returns a view (a reference to the original data), rather than copying the data. This is more memory-efficient
and faster compared to Python lists, where slicing results in a new list with copied elements.
'''
#Example: Slicing Efficiency

import numpy as np

# NumPy array slicing (returns a view, no data copying)
arr_np = np.arange(1000000)
sub_arr_np = arr_np[100:200]

# Python list slicing (returns a new list, copies data)
arr_py = list(range(1000000))
sub_arr_py = arr_py[100:200]
#In NumPy, slicing is much faster because it avoids copying data, which is not the case with Python lists.

NumPy array memory usage: 4000000 bytes
Python list memory usage: 8000056 bytes
NumPy operation time: 0.007699251174926758
Python list operation time: 0.18040680885314941
NumPy result with broadcasting: [6 7 8 9]
NumPy sum time: 0.0013432502746582031
Python list sum time: 0.013324737548828125
[[1 4]
 [2 5]
 [3 6]]


In [3]:
# QUESTION 7
# Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.
'''
In NumPy, both vstack() and hstack() are functions used to stack arrays along different axes. They allow you to combine multiple arrays into a single array but in different orientations.

1. np.vstack() (Vertical Stack)
vstack() stacks arrays vertically, i.e., row-wise.
The arrays are joined along the vertical axis (axis 0). This is equivalent to concatenation along rows.
'''
#Example:

import numpy as np

# Create two 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Vertically stack the arrays
result = np.vstack((array1, array2))

print(result)

#Here, vstack() stacks the arrays one on top of the other, resulting in a 2D array with two rows.

#For 2D arrays:

# Create two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])

# Vertically stack the arrays
result = np.vstack((array1, array2))

print(result)

#In this case, vstack() stacks the second array below the first one.
'''
2. np.hstack() (Horizontal Stack)
hstack() stacks arrays horizontally, i.e., column-wise.
The arrays are joined along the horizontal axis (axis 1). This is equivalent to concatenation along columns.
'''
#Example:

# Create two 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Horizontally stack the arrays
result = np.hstack((array1, array2))

print(result)

#In this case, hstack() creates a single row by appending the second array to the first.

#For 2D arrays:
# Create two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Horizontally stack the arrays
result = np.hstack((array1, array2))

print(result)

#Here, hstack() appends the columns of the second array to the columns of the first one, resulting in a 2D array with more columns.
'''
Key Differences
vstack() stacks arrays along the vertical axis (axis 0) — row-wise. This increases the number of rows.
hstack() stacks arrays along the horizontal axis (axis 1) — column-wise. This increases the number of columns.
When to Use:
Use vstack() when you want to add rows to an array.
Use hstack() when you want to add columns to an array.
Both functions are commonly used when combining data or results from multiple operations, especially when reshaping data for analysis or modeling.
'''



[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]


'\nKey Differences\nvstack() stacks arrays along the vertical axis (axis 0) — row-wise. This increases the number of rows.\nhstack() stacks arrays along the horizontal axis (axis 1) — column-wise. This increases the number of columns.\nWhen to Use:\nUse vstack() when you want to add rows to an array.\nUse hstack() when you want to add columns to an array.\nBoth functions are commonly used when combining data or results from multiple operations, especially when reshaping data for analysis or modeling.\n'

In [4]:
#QUESTION 8
# Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

#Differences between fliplr() and flipud():
'''
fliplr() flips an array horizontally, meaning it reverses the order of columns. It's typically used for 2D arrays and higher-dimensional arrays.

flipud() flips an array vertically, meaning it reverses the order of rows. Like fliplr(), it's also used for 2D arrays and beyond.
'''

#fliplr() Example:

import numpy as np

array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

flipped_lr = np.fliplr(array_2d)
print("Original Array:\n", array_2d)
print("Flipped Left-Right:\n", flipped_lr)

#flipud() Example:

flipped_ud = np.flipud(array_2d)
print("Flipped Up-Down:\n", flipped_ud)
'''
Key Points:
fliplr() flips an array horizontally (left-right) by reversing the order of columns.
flipud() flips an array vertically (up-down) by reversing the order of rows.
For 1D arrays, both functions have the same effect of reversing the elements because there is only one axis.
For 3D arrays, each function affects only the specific axis they are meant to flip.
'''

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flipped Left-Right:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Flipped Up-Down:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


'\nKey Points:\nfliplr() flips an array horizontally (left-right) by reversing the order of columns.\nflipud() flips an array vertically (up-down) by reversing the order of rows.\nFor 1D arrays, both functions have the same effect of reversing the elements because there is only one axis.\nFor 3D arrays, each function affects only the specific axis they are meant to flip.\n'

In [6]:
#QUESTION 9
#Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
'''
The array_split() method in NumPy is used to split an array into multiple sub-arrays. Unlike split(), which requires that the splits divide the
array evenly, array_split() can handle uneven splits by distributing the remainder across the sub-arrays.

Key Functionality of array_split():
General Behavior:
The method splits an array into specified sections. You can define the number of sections you want the array to be split into.
If the array cannot be split evenly, array_split() will divide the array as equally as possible, with the remaining elements distributed across the earlier sub-arrays.
'''
#np.array_split(array, sections)
'''
array: The input array you want to split.
sections: The number of equal parts (or sections) you want to split the array into.
Handling Uneven Splits:
If the array size isn't divisible by the number of sections, array_split() will create sub-arrays where the extra elements are distributed starting from the first sub-array. As a result, some sub-arrays may have one more element than others.
'''
#Example of Even Split:

import numpy as np

# Create an array
array = np.array([1, 2, 3, 4, 5, 6])

# Split into 3 equal parts
result = np.array_split(array, 3)

print(result)

#In this case, the array is divided evenly into 3 sub-arrays.

#Example of Uneven Split:

# Create an array
array = np.array([1, 2, 3, 4, 5, 6, 7])

# Split into 3 parts (not evenly divisible)
result = np.array_split(array, 3)

print(result)

#Here, the array size (7) isn't divisible by 3, so the first sub-array gets an extra element. The first sub-array has 3 elements, while the others have 2.
'''
Differences from split():
The split() method throws an error if the array cannot be split evenly into the specified sections, while array_split() handles uneven splits gracefully
by distributing the remainder.
Use Case:
array_split() is useful when you don't know the exact number of elements or when the size of the array might not divide evenly by the desired number of
splits. It ensures that every part gets a nearly equal number of elements.
'''

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2, 3]), array([4, 5]), array([6, 7])]


"\nDifferences from split():\nThe split() method throws an error if the array cannot be split evenly into the specified sections, while array_split() handles uneven splits gracefully \nby distributing the remainder.\nUse Case:\narray_split() is useful when you don't know the exact number of elements or when the size of the array might not divide evenly by the desired number of \nsplits. It ensures that every part gets a nearly equal number of elements.\n"

In [7]:
#QUESTION 10
#Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
'''
1. Vectorization in NumPy:
Vectorization is the process of performing operations on entire arrays (or large chunks of data) without using explicit loops. This allows you to apply operations
element-wise on arrays, leveraging optimized low-level implementations to significantly speed up computation.

In traditional Python, loops are used to iterate over data. However, in NumPy, vectorized operations replace these loops, making the code not only more efficient
but also more concise and readable.
'''
#Example of Vectorization:

import numpy as np

# Create two arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Vectorized addition
result = a + b
print(result)

#Here, the addition of two arrays is done element-wise without the need for loops. This vectorized operation is much faster than writing a loop to add individual elements.
'''
Advantages of Vectorization:
Speed: Operations are performed using low-level C or Fortran routines optimized for performance.
Code simplicity: Complex operations can be written concisely in one line of code, reducing errors and improving readability.
2. Broadcasting in NumPy:
Broadcasting is a feature that allows NumPy to perform operations on arrays of different shapes, by "stretching" or replicating the smaller array across
the larger one, without physically copying the data. It enables element-wise operations between arrays with different shapes.

For broadcasting to work, the smaller array's shape must either match the larger array's shape or be compatible following specific rules:

If the two arrays have a different number of dimensions, the smaller array is padded with extra dimensions at the beginning.
If the shape of the arrays doesn’t match, the dimension of size 1 in the smaller array is “stretched” to match the size of the corresponding dimension in the larger array.
'''
#Example of Broadcasting:

import numpy as np

# Create an array
a = np.array([1, 2, 3])

# Create a scalar
b = 5

# Broadcasting: scalar b is applied to each element of array a
result = a + b
print(result)


#In this example, the scalar b is broadcasted across the array a, meaning 5 is added to each element of a without needing an explicit loop.

#More Complex Example of Broadcasting:

# Create a 2D array
a = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 1D array
b = np.array([1, 2, 3])

# Broadcasting: the 1D array is stretched to match the shape of the 2D array
result = a + b
print(result)

#Here, the 1D array b is broadcasted across the rows of the 2D array a, adding element-wise.
'''
Advantages of Broadcasting:
Memory efficiency: Broadcasting avoids creating copies of arrays, instead operating on views of the original data.
Simplified code: It allows you to perform operations on arrays with different shapes without having to manually resize or reshape them.
How Vectorization and Broadcasting Contribute to Efficient Array Operations:
Speed: Both vectorization and broadcasting eliminate the need for explicit Python loops, allowing operations to be carried out by optimized C-level code, which runs much faster.

Memory Efficiency: Broadcasting allows for operations on arrays of different shapes without creating unnecessary copies, which saves memory.

Conciseness: These concepts make the code more concise and easier to write, maintain, and debug.
'''

[ 6  8 10 12]
[6 7 8]
[[2 4 6]
 [5 7 9]]


'\nAdvantages of Broadcasting:\nMemory efficiency: Broadcasting avoids creating copies of arrays, instead operating on views of the original data.\nSimplified code: It allows you to perform operations on arrays with different shapes without having to manually resize or reshape them.\nHow Vectorization and Broadcasting Contribute to Efficient Array Operations:\nSpeed: Both vectorization and broadcasting eliminate the need for explicit Python loops, allowing operations to be carried out by optimized C-level code, which runs much faster.\n\nMemory Efficiency: Broadcasting allows for operations on arrays of different shapes without creating unnecessary copies, which saves memory.\n\nConciseness: These concepts make the code more concise and easier to write, maintain, and debug.\n'

**PRACTICAL QUESTION**

In [15]:
#QUESTION 1
# Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np
arr=np.random.randint(1,100,(3,3))
# interchanging raw and columns
arr1=arr.T
arr #3x3 array with random integers
arr1 # transpose of arr

array([[49,  4, 59],
       [32, 32, 55],
       [58, 67, 21]])

In [17]:
# QUESTION 2
#Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array
arr2=np.arange(10)
arr2
arr2.reshape(2,5) #reshape it into 2x5
arr2.reshape(5,2) #reshape it into 5x2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [19]:
# QUESTION 3
# Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
arr3=np.random.rand(4,4)
arr3
arr3,np.pad(arr3,pad_width=1,constant_values=0)

(array([[0.98295803, 0.42092234, 0.98049825, 0.66917559],
        [0.03135296, 0.79277238, 0.66752496, 0.43645359],
        [0.45821445, 0.26640105, 0.44867981, 0.42578816],
        [0.32759665, 0.81260725, 0.53127026, 0.39601539]]),
 array([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.98295803, 0.42092234, 0.98049825, 0.66917559,
         0.        ],
        [0.        , 0.03135296, 0.79277238, 0.66752496, 0.43645359,
         0.        ],
        [0.        , 0.45821445, 0.26640105, 0.44867981, 0.42578816,
         0.        ],
        [0.        , 0.32759665, 0.81260725, 0.53127026, 0.39601539,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ]]))

In [21]:
# QUESTION 4
# Using NumPy, create an array of integers from 10 to 60 with a step of 5
arr4=np.arange(10,60,5)
arr4

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [24]:
# QUESTION 5
#reate a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.
arr5=np.array(['python','numpy','pandas'])
arr5
a=np.char.upper(arr5) #uppercase
b=np.char.lower(arr5) #lowercase
c=np.char.title(arr5) #title case
a,b,c

(array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6'),
 array(['python', 'numpy', 'pandas'], dtype='<U6'),
 array(['Python', 'Numpy', 'Pandas'], dtype='<U6'))

In [28]:
#QUESTION 6
#Generate a NumPy array of words. Insert a space between each character of every word in the array.
arr=np.array(['python','numpy','pandas'])
arr
np.char.join(' ',arr)

array(['p y t h o n', 'n u m p y', 'p a n d a s'], dtype='<U11')

In [36]:
#QUESTION 7
#Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
arr=np.random.randint(1,20,(3,3))
arr1=np.random.randint(1,20,(3,3))
arr,arr1
a=arr+arr1 #addition
b=arr-arr1 #subtraction
c=arr*arr1 #multiplication
d=arr/arr1 #division
a,b,c,d

(array([[29, 15,  5],
        [20, 35, 21],
        [19, 32, 27]]),
 array([[-3,  9,  1],
        [-6, -3, -7],
        [ 9, -6,  3]]),
 array([[208,  36,   6],
        [ 91, 304,  98],
        [ 70, 247, 180]]),
 array([[0.8125    , 4.        , 1.5       ],
        [0.53846154, 0.84210526, 0.5       ],
        [2.8       , 0.68421053, 1.25      ]]))

In [39]:
#QUESTION 8
# Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
arr=np.eye(5,dtype=int)
arr
arr,np.diag(arr)

(array([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]]),
 array([1, 1, 1, 1, 1]))

In [42]:
#QUESTION 9
# Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

# Display the results
print("Random Integers:", random_integers)
print("Prime Numbers:", prime_numbers)


Random Integers: [ 405  187  389  781  118  649  640  853  334  539  262  552  429  416
  235  349  650  453  430  740  133  234  419  962  564  170  540  621
  865  352  566   36   81  161  795  110  950  931  811  474  404   53
  693  872  641  753  824  763  391  562  178  735  589  857  143  588
  656  848   46   44  154  614  326  881  589   29    0  408  434  395
  973  601  105  561   89  879  634  807  107 1000  832  662  939  193
  467  242  985  397  257  993  554  254  860  141  870  395  820  980
  294  916]
Prime Numbers: [389, 853, 349, 419, 811, 53, 641, 857, 881, 29, 601, 89, 107, 193, 467, 397, 257]


In [45]:
#Question 10
# Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

import numpy as np

# Create a NumPy array representing daily temperatures for 30 days
# Generating random temperatures between 15 and 35 degrees Celsius
daily_temperatures = np.random.randint(15, 36, size=30).astype(float)

# Reshape the array to have 4 weeks (7 days each) and an additional 2 days for the last week
# If the number of days isn't a multiple of 7, pad with NaN for consistency
if len(daily_temperatures) % 7 != 0:
    padding = 7 - (len(daily_temperatures) % 7)
    daily_temperatures = np.pad(daily_temperatures, (0, padding), constant_values=np.nan)

# Reshape the temperatures into a 2D array (weeks x days)
weekly_temperatures = daily_temperatures.reshape(-1, 7)

# Calculate the weekly averages, ignoring NaN values
weekly_averages = np.nanmean(weekly_temperatures, axis=1)

# Display the results
print("Daily Temperatures for the Month:", daily_temperatures)
print("Weekly Averages:", weekly_averages)


Daily Temperatures for the Month: [16. 16. 22. 25. 16. 28. 29. 15. 22. 18. 34. 21. 33. 33. 25. 31. 17. 34.
 29. 32. 25. 15. 22. 32. 18. 16. 20. 29. 26. 25. nan nan nan nan nan]
Weekly Averages: [21.71428571 25.14285714 27.57142857 21.71428571 25.5       ]
